#!/bin/bash 
#SBATCH --nodes=16
#SBATCH --ntasks-per-node=16
#SBATCH --job-name=HadoopTest
#SBATCH --output=Tile-6-256.out
#SBATCH --time=36:00:00

source /software/hadoop-1.1.2-el6-x86_64/bin/midway-hadoop.sh

# Use the predefined Midway configuration source
hadoop namenode -format
start-all.sh 

# Write test hadoop jar
/software/python-3.3-el6-x86_64/bin/python3 run.py 6 6 6 108 hadoop 1

stop-all.sh

